---
sidebar: sidebar 
permalink: docs/concept_nde_access_overview.html 
summary: Accéder au moteur de déploiement NetApp avant de déployer NetApp HCI de plusieurs méthodes, selon votre environnement. 
keywords: netapp, hci, netapp deployment engine, deployment, engine, deploy, access 
---
= Présentation des options d'accès du moteur de déploiement NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: hci, release notes, vcp, element, management services, firmware


[role="lead"]
Pour déployer NetApp HCI, vous devez accéder au moteur de déploiement NetApp sur l'un des nœuds de stockage NetApp H-Series via l'adresse IPv4 attribuée à l'interface Bond1G, qui correspond à l'interface logique qui combine les ports A et B pour les nœuds de stockage. Ce nœud de stockage devient le noeud de stockage de contrôle pour le processus de déploiement. Selon votre environnement, vous devez configurer l'adresse IPv4 ou la récupérer à partir de l'un des nœuds de stockage.


NOTE: Vous pouvez uniquement accéder au moteur de déploiement NetApp à l'aide de l'interface Bond1G d'un nœud de stockage. L'interface logique qui combine les ports C et D pour les nœuds de stockage n'est pas prise en charge grâce à l'interface Bond10G.

Utilisez l'une des méthodes suivantes qui décrit le mieux votre environnement réseau pour accéder au moteur de déploiement NetApp :

|===
| Scénario | Méthode 


| Vous ne disposez pas de DHCP dans votre environnement | link:task_nde_access_no_dhcp.html["Accédez au moteur de déploiement NetApp dans des environnements sans DHCP"] 


| Le DHCP est présent dans votre environnement | link:task_nde_access_dhcp.html["Accès au moteur de déploiement NetApp dans des environnements avec DHCP"] 


| Vous souhaitez attribuer toutes les adresses IP manuellement | link:task_nde_access_manual_ip.html["Attribuez manuellement des adresses IP pour accéder au moteur de déploiement NetApp"] 
|===
[discrete]
== Trouvez plus d'informations

* link:task_nde_access_ui_fqdn.html["Configurez l'accès à l'interface utilisateur Web du nom de domaine complet"^]

