---
sidebar: sidebar 
permalink: docs/reference_hcc_config_maximums.html 
summary: NetApp Hybrid Cloud Control comprend des fonctionnalités spécifiques. NetApp recommande de travailler avec ces fonctionnalités. 
keywords: netapp, hci, HCC, configuration, capabilities, limits, maximums 
---
= Valeurs maximales de configuration NetApp pour Cloud Control
:allow-uri-read: 


[role="lead"]
NetApp HCI inclut NetApp Hybrid Cloud Control pour simplifier la gestion du cycle de vie du calcul et du stockage. Cette solution prend en charge les mises à niveau du logiciel Element sur des nœuds de stockage pour les clusters de stockage NetApp HCI et NetApp SolidFire, ainsi que les mises à niveau du firmware pour les nœuds de calcul NetApp HCI dans NetApp HCI. Elle est disponible par défaut sur les nœuds de gestion dans NetApp HCI.

Outre la communication des composants matériels et logiciels fournis par NetApp dans une installation NetApp HCI, NetApp Hybrid Cloud Control interagit avec des composants tiers dans l'environnement client, tels que VMware vCenter. NetApp qualifie la fonctionnalité de NetApp de cloud hybride Control et son interaction avec ces composants tiers dans l'environnement du client à une certaine échelle. Pour optimiser l'expérience avec NetApp Hybrid Cloud Control, NetApp recommande de rester dans la plage maximale de configuration.

Si vous dépassez ces limites testées, la commande de cloud hybride NetApp peut rencontrer des problèmes avec une interface utilisateur et des réponses d'API plus lentes ou fonctionnalité n'étant pas disponible. Si vous faites appel à NetApp pour la prise en charge des produits avec NetApp Cloud Control dans des environnements configurés en dehors des limites de configuration, le support NetApp vous demande de modifier la configuration afin qu'elle respecte les valeurs maximales de configuration documentées.

.Valeurs maximales de configuration
NetApp Hybrid Cloud Control prend en charge les environnements VMware vSphere avec jusqu'à 500 nœuds de calcul NetApp. Il prend en charge jusqu'à 20 clusters de stockage NetApp Element avec 40 nœuds de stockage par cluster.
