---
sidebar: sidebar 
permalink: docs/task_hci_credentials_vcenter_esxi.html 
summary: 'Lors d"une installation NetApp HCI, vous pouvez modifier les identifiants des hôtes vCenter et ESXi pour un nœud de calcul géré par NetApp Hybrid Cloud Control.' 
keywords: netapp, hci, password, credential, vcenter, esxi, hybrid cloud control 
---
= Mettre à jour les identifiants vCenter et ESXi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour que votre installation NetApp HCI puisse bénéficier de tous les fonctionnalités de NetApp Hybrid Cloud Control, lorsque vous modifiez vos identifiants dans les hôtes vCenter et ESXi, vous devez également mettre à jour ces identifiants dans le service des ressources du nœud de gestion.

NetApp Hybrid Cloud Control communique avec vCenter et les nœuds de calcul individuels exécutant VMware vSphere ESXi afin d'obtenir des informations concernant le tableau de bord et de faciliter la mise à niveau du firmware, des logiciels et des pilotes. NetApp Hybrid Cloud Control et ses services associés disponibles sur le nœud de gestion utilisent les identifiants (nom d'utilisateur/mot de passe) pour vous authentifier auprès de VMware vCenter et ESXi.

Si la communication entre ces composants tombe en panne, NetApp Hybrid Cloud Control et vCenter affichent des messages d'erreur lorsqu'un problème d'authentification se produit. La commande de cloud hybride NetApp affiche une bannière d'erreur rouge si elle ne peut pas communiquer avec l'instance VMware vCenter associée lors de l'installation d'NetApp HCI. VMware vCenter affiche les messages de verrouillage des comptes ESXi pour les hôtes ESXi individuels grâce à NetApp Hybrid Cloud Control et utilise des informations d'identification obsolètes.

Le nœud de gestion dans NetApp HCI utilise les noms suivants pour ces composants :

* Les « actifs du contrôleur » sont des instances vCenter associées à votre installation NetApp HCI.
* Les « ressources de nœud de calcul » sont les hôtes ESXi de votre installation NetApp HCI.


Lors de l'installation initiale de NetApp HCI à l'aide du moteur de déploiement NetApp, le nœud de gestion stockait les identifiants de l'utilisateur d'administration spécifié pour vCenter et le mot de passe du compte « root » sur les serveurs ESXi.



== Mettez à jour le mot de passe vCenter à l'aide de l'API REST du nœud de gestion

Suivez les étapes pour mettre à jour les actifs du contrôleur. Voir link:task_mnode_edit_vcenter_assets.html["Afficher ou modifier des actifs de contrôleur existants"].



== Mettez à jour le mot de passe ESXi à l'aide de l'API REST du nœud de gestion

.Étapes
. Pour obtenir une vue d'ensemble de l'interface utilisateur de l'API REST de nœud de gestion, reportez-vous à la section link:task_mnode_work_overview_API.html["Présentation de l'interface utilisateur de l'API REST du nœud de gestion"].
. Accès à l'interface d'API REST pour les services de gestion sur le nœud de gestion :
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
Remplacez <IP du nœud de gestion> par l'adresse IPv4 de votre nœud de gestion sur le réseau de gestion utilisé pour NetApp HCI.

. Cliquez sur *Authorise* ou sur une icône de verrouillage et procédez comme suit :
+
.. Entrez le nom d'utilisateur et le mot de passe d'administration du cluster NetApp SolidFire.
.. Saisissez l'ID client en tant que `mnode-client`.
.. Cliquez sur *Autoriser* pour démarrer une session.
.. Fermez la fenêtre.


. Dans l'interface utilisateur de l'API REST, cliquez sur *OBTENIR ​/Assets/Compute_nodes*.
+
Cela récupère les enregistrements des ressources du nœud de calcul stockées dans le nœud de gestion.

+
Voici le lien direct vers cette API dans l'interface utilisateur :

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.get_compute_nodes
----
. Cliquez sur *essayez-le*.
. Cliquez sur *Exécuter*.
. Dans le corps de réponse, identifiez les enregistrements d'actifs du nœud de calcul qui nécessitent des informations d'identification mises à jour. Vous pouvez utiliser les propriétés “ip” et “host_name” pour trouver les enregistrements hôtes VMware ESXi corrects.
+
[listing]
----
"config": { },
"credentialid": <credential_id>,
"hardware_tag": <tag>,
"host_name": <host_name>,
"id": <id>,
"ip": <ip>,
"parent": <parent>,
"type": ESXi Host
----
+

NOTE: L’étape suivante utilise les champs “parent” et “ID” de l’enregistrement de ressource de calcul pour référencer l’enregistrement à mettre à jour.

. Configurez la ressource de nœud de calcul spécifique :
+
.. Cliquez sur *PUT /Assets/{ASSET_ID}/Compute-nodes/{Compute_ID}*.
+
Voici le lien direct vers l'API dans l'interface utilisateur :

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.put_assets_compute_id
----
.. Cliquez sur *essayez-le*.
.. Entrez l’ID_ressource avec les informations “parent”.
.. Entrez “Compute_ID” avec les informations “ID”.
.. Modifiez le corps de la demande dans l'interface utilisateur pour ne mettre à jour que les paramètres de mot de passe et de nom d'utilisateur dans l'enregistrement de ressource de calcul :
+
[listing]
----
{
"password": "<password>",
"username": "<username>"
}
----
.. Cliquez sur *Exécuter*.
.. Vérifiez que la réponse est HTTP 200, ce qui indique que les nouvelles informations d'identification ont été stockées dans l'enregistrement des ressources de calcul référencées


. Répétez les deux étapes précédentes pour les ressources de nœud de calcul supplémentaires qui doivent être mises à jour avec un nouveau mot de passe.
. Accédez à https://<mNode_ip>/inventory/1/[].
+
.. Cliquez sur *Authorise* ou sur une icône de verrouillage et procédez comme suit :
+
... Entrez le nom d'utilisateur et le mot de passe d'administration du cluster NetApp SolidFire.
... Saisissez l'ID client en tant que `mnode-client`.
... Cliquez sur *Autoriser* pour démarrer une session.
... Fermez la fenêtre.


.. Dans l'interface utilisateur de l'API REST, cliquez sur *OBTENIR /installations*.
.. Cliquez sur *essayez-le*.
.. Sélectionnez *vrai* dans la liste déroulante de description d'actualisation.
.. Cliquez sur *Exécuter*.
.. Vérifiez que la réponse est HTTP 200.


. Attendez environ 15 minutes que le message de verrouillage de compte disparaisse dans vCenter.


[discrete]
== Trouvez plus d'informations

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["Page Ressources NetApp HCI"^]

