---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_storage_firmware.html 
summary: 'Dans le cadre de la mise à niveau d"un système NetApp HCI, vous mettez à niveau le firmware associé à vos nœuds de stockage.' 
keywords: netapp, element, hcc, firmware, storage firmware 
---
= Mettre à niveau le firmware du stockage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
À partir d'Element 12.0 et des services de gestion version 2.14, vous pouvez effectuer des mises à niveau firmware uniquement sur vos nœuds de stockage à l'aide de l'interface utilisateur NetApp Hybrid Cloud Control et de l'API REST. Cette procédure ne met pas à niveau le logiciel Element et vous permet de mettre à niveau le firmware du stockage en dehors de la version d'un élément majeur.

.Ce dont vous avez besoin
* *Privilèges d'administrateur* : vous disposez des autorisations d'administrateur du cluster de stockage pour effectuer la mise à niveau.
* *Synchronisation de l'heure du système* : vous avez vérifié que l'heure du système sur tous les nœuds est synchronisée et que NTP est correctement configuré pour le cluster de stockage et les nœuds. Chaque nœud doit être configuré avec un serveur de noms DNS dans l'interface utilisateur Web par nœud (`https://[IP address]:442`) sans erreurs de cluster non résolues liées à l'inclinaison temporelle.
* *Ports système* : si vous utilisez le contrôle du cloud hybride NetApp pour les mises à niveau, vous avez vérifié que les ports nécessaires sont ouverts. Voir link:hci_prereqs_required_network_ports.html["Ports réseau"] pour en savoir plus.
* *Nœud de gestion* : pour l'interface utilisateur et l'API de contrôle de cloud hybride NetApp, le nœud de gestion de votre environnement exécute la version 11.3.
* *Services de gestion*: Vous avez mis à jour votre bundle de services de gestion à la dernière version.



IMPORTANT: Pour les nœuds de stockage H610S exécutant la version 12.0 du logiciel Element, vous devez appliquer le correctif SUST-909 avant de mettre à niveau le pack du firmware du stockage 2.27. Contactez le support NetApp pour obtenir le D-patch avant de procéder à la mise à niveau. Voir link:rn_storage_firmware_2.27.html["Notes de version du pack de firmware de stockage 2.27"].


IMPORTANT: Vous devez effectuer la mise à niveau vers le dernier bundle de services de gestion avant de mettre à niveau le firmware de vos nœuds de stockage. Si vous mettez à jour votre logiciel Element vers la version 12.2 ou ultérieure, vous avez besoin des services de gestion 2.14.60 ou version ultérieure pour continuer.


IMPORTANT: Pour mettre à jour le micrologiciel iDRAC/BIOS, contactez le support NetApp. Pour plus d'informations, reportez-vous à ce document link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/SF_Series/How_to_update_iDRAC%2F%2FBIOS_firmware_on_SF_Series_nodes["Article de la base de connaissances"^].

* *Cluster Health* : vous avez effectué des vérifications d'intégrité. Voir link:task_hcc_upgrade_element_prechecks.html["Exécutez des vérifications de l'état du stockage Element avant la mise à niveau du stockage"].
* *Mise à jour de BMC pour les nœuds H610S*: Vous avez mis à niveau la version de BMC pour vos nœuds H610S. Voir link:rn_H610S_BMC_3.84.07.html["notes de version et instructions de mise à niveau"].



NOTE: Pour obtenir une matrice complète de micrologiciel et de micrologiciel de pilote pour votre matériel, reportez-vous à ce document https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software["Article de la base de connaissances"^] (connexion requise).

* *Contrat de licence utilisateur final (CLUF)* : à partir des services de gestion 2.20.69, vous devez accepter et enregistrer le CLUF avant d'utiliser l'interface utilisateur ou l'API de contrôle du cloud hybride NetApp pour mettre à niveau le micrologiciel de stockage :
+
.. Ouvrez l'adresse IP du nœud de gestion dans un navigateur Web :
+
[listing]
----
https://<ManagementNodeIP>
----
.. Connectez-vous au contrôle de cloud hybride NetApp en fournissant les identifiants de l'administrateur du cluster de stockage.
.. Sélectionnez *Upgrade* en haut à droite de l'interface.
.. Le CLUF s'affiche. Faites défiler vers le bas, sélectionnez *J'accepte les mises à jour actuelles et futures*, puis sélectionnez *Enregistrer*.
+

NOTE: Lorsque vous acceptez le CLUF, il est enregistré pour toutes les mises à jour futures et la fonction de téléchargement automatique est activée. Vous recevrez des mises à jour sur les mises à jour et les mises à niveau logicielles NetApp que vous pouvez installer à votre discrétion et à votre convenance. Vous pouvez désactiver la fonctionnalité de téléchargement automatique en désactivant la connectivité réseau au référentiel logiciel en ligne de NetApp.





.Options de mise à niveau
Choisissez l'une des options de mise à niveau du micrologiciel de stockage suivantes :

* <<Utilisez l'interface de contrôle du cloud hybride NetApp pour la mise à niveau du firmware du stockage>>
* <<Utilisez l'API de contrôle de cloud hybride NetApp pour mettre à niveau le firmware du stockage>>




== Utilisez l'interface de contrôle du cloud hybride NetApp pour la mise à niveau du firmware du stockage

Vous pouvez utiliser l'interface utilisateur de NetApp Hybrid Cloud Control pour mettre à niveau le firmware des nœuds de stockage dans votre cluster.

.Ce dont vous avez besoin
Si votre nœud de gestion n'est pas connecté à Internet, vous l'avez https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab/download/62654/Storage_Firmware_Bundle["Le pack du firmware de stockage des clusters de stockage NetApp HCI a été téléchargé"^].


CAUTION: Pour les problèmes potentiels lors de la mise à niveau des clusters de stockage à l'aide de NetApp Hybrid Cloud Control et de solutions de contournement de ces problèmes, consultez le https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["Article de la base de connaissances"^].


TIP: Le processus de mise à niveau prend environ 30 minutes par nœud de stockage. Si vous mettez à niveau un cluster de stockage Element vers la version 2.76 du firmware du stockage, des nœuds de stockage individuels ne redémarreront que durant la mise à niveau si le nouveau firmware est écrit sur le nœud.

.Étapes
. Ouvrez l'adresse IP du nœud de gestion dans un navigateur Web :
+
[listing]
----
https://<ManagementNodeIP>
----
. Connectez-vous au contrôle de cloud hybride NetApp en fournissant les identifiants de l'administrateur du cluster de stockage.
. Sélectionnez *Upgrade* en haut à droite de l'interface.
. Sur la page *mises à niveau*, sélectionnez *stockage*.
+

NOTE: L'onglet *Storage* répertorie les clusters de stockage qui font partie de votre installation. Si un cluster n'est pas accessible via NetApp Hybrid Cloud Control, il ne s'affiche pas sur la page *mises à niveau*. Si vous avez des clusters exécutant Element 12.0 ou une version ultérieure, la version actuelle des packs de firmware est répertoriée pour ces clusters. Si les nœuds d'un cluster ont des versions de micrologiciel différentes ou lorsque la mise à niveau progresse, vous verrez *multiple* dans la colonne *version actuelle du bundle de micrologiciels*. Vous pouvez sélectionner *multiple* pour accéder à la page *Nodes* pour comparer les versions du micrologiciel. Si tous les clusters exécutent des versions Element avant la version 12.0, aucune information concernant les numéros de version des packs de firmware n'apparaît. Ces informations sont également disponibles sur la page *Nodes*. Voir link:task_hcc_nodes.html["Afficher votre inventaire"]. Si le cluster est à jour et/ou qu'aucun package de mise à niveau n'est disponible, les onglets *Element* et *Firmware Only* ne s'affichent pas. Ces onglets ne s'affichent pas également lorsqu'une mise à niveau est en cours. Si l'onglet *Element* est affiché mais pas l'onglet *Firmware Only*, aucun progiciel de microprogramme n'est disponible.

. Choisissez l'une des options suivantes et effectuez l'ensemble des étapes applicables au cluster :
+
[cols="2*"]
|===
| Option | Étapes 


| Votre nœud de gestion dispose d'une connectivité externe.  a| 
.. Sélectionnez la flèche de liste déroulante située à côté du cluster que vous mettez à niveau.
.. Sélectionnez *Firmware Only*, puis choisissez parmi les versions de mise à niveau disponibles.
.. Sélectionnez *commencer la mise à niveau*.



TIP: Le *Statut de mise à niveau* change pendant la mise à niveau pour refléter l'état du processus. Elle change également en réponse aux actions que vous avez effectuées, comme la mise en pause de la mise à niveau, ou si la mise à niveau renvoie une erreur. Voir <<Modifications du statut des mises à niveau>>.


NOTE: Pendant que la mise à niveau est en cours, vous pouvez quitter la page et y revenir plus tard pour continuer à suivre la progression. La page ne met pas à jour dynamiquement l'état et la version actuelle si la ligne du cluster est réduite. La ligne du cluster doit être développée pour mettre à jour la table ou vous pouvez actualiser la page.

Vous pouvez télécharger les journaux une fois la mise à niveau terminée.



| Votre nœud de gestion se trouve dans un site sombre sans connectivité externe.  a| 
.. Sélectionnez la flèche de liste déroulante située à côté du cluster que vous mettez à niveau.
.. Sélectionnez *Parcourir* pour télécharger le package de mise à niveau que vous avez téléchargé.
.. Attendez la fin du chargement. Une barre de progression indique l'état du téléchargement.



CAUTION: Le téléchargement du fichier sera perdu si vous vous éloignez de la fenêtre du navigateur.

Un message à l'écran s'affiche une fois le fichier téléchargé et validé. La validation peut prendre plusieurs minutes. Si vous ne vous éloignez pas de la fenêtre du navigateur à ce stade, le téléchargement du fichier est conservé. Vous pouvez télécharger les journaux une fois la mise à niveau terminée. Pour plus d'informations sur les différentes modifications de l'état de mise à niveau, reportez-vous à la section <<Modifications du statut des mises à niveau>>.

|===




=== Modifications du statut des mises à niveau

Voici les différents États que la colonne *Upgrade Status* de l'interface utilisateur affiche avant, pendant et après le processus de mise à niveau :

[cols="2*"]
|===
| État de mise à niveau | Description 


| À jour | Le cluster a été mis à niveau vers la dernière version d'Element disponible ou le micrologiciel a été mis à niveau vers la dernière version. 


| Détection impossible | NetApp Hybrid Cloud Control affiche ce statut au lieu de *versions disponibles* lorsqu'il ne dispose pas d'une connectivité externe pour accéder au référentiel logiciel en ligne. Cet état est également affiché lorsque l'API du service de stockage renvoie un état de mise à niveau qui ne figure pas dans la liste énumérée des États de mise à niveau possibles. 


| Versions disponibles | Des versions plus récentes du firmware Element et/ou de stockage sont disponibles pour la mise à niveau. 


| En cours | La mise à niveau est en cours. Une barre de progression indique l'état de la mise à niveau. Les messages à l'écran affichent également les défaillances au niveau du nœud et l'ID de nœud de chaque nœud du cluster au fur et à mesure de la mise à niveau. Vous pouvez contrôler l'état de chaque nœud via l'interface utilisateur Element ou le plug-in NetApp Element pour l'interface utilisateur de vCenter Server. 


| Mise à niveau en pause | Vous pouvez choisir d'interrompre la mise à niveau. Selon l'état du processus de mise à niveau, l'opération de pause peut réussir ou échouer. Une invite de l'interface utilisateur s'affiche pour vous demander de confirmer l'opération de pause. Pour vérifier que le cluster est bien en place avant d'interrompre une mise à niveau, il peut prendre jusqu'à deux heures pour que l'opération de mise à niveau soit complètement suspendue. Pour reprendre la mise à niveau, sélectionnez *reprendre*. 


| En pause | Vous avez interrompu la mise à niveau. Sélectionnez *reprendre* pour reprendre le processus. 


| Erreur | Une erreur s'est produite lors de la mise à niveau. Vous pouvez télécharger le journal des erreurs et l'envoyer au support NetApp. Après avoir résolu l'erreur, vous pouvez revenir à la page et sélectionner *reprendre*. Lorsque vous reprenez la mise à niveau, la barre de progression revient en arrière pendant quelques minutes pendant que le système exécute la vérification de l'état et vérifie l'état actuel de la mise à niveau. 
|===


== Que se passe-t-il si une mise à niveau échoue avec NetApp Hybrid Cloud Control

En cas de panne d'un disque ou d'un nœud lors de la mise à niveau, l'interface d'Element affiche les défaillances de cluster. Le processus de mise à niveau ne se poursuit pas vers le nœud suivant et attend que les pannes du cluster soient résolu. La barre de progression dans l'interface utilisateur indique que la mise à niveau attend la résolution des pannes du cluster. À ce stade, la sélection de *Pause* dans l'interface utilisateur ne fonctionnera pas, car la mise à niveau attend que le cluster fonctionne correctement. Vous devrez faire appel au support NetApp pour résoudre le problème.

Le contrôle du cloud hybride NetApp offre une période d'attente prédéfinie de trois heures. Pour ce faire, vous pouvez utiliser l'un des scénarios suivants :

* Les pannes de cluster sont résolues dans une fenêtre de trois heures, puis une mise à niveau est rétablie. Vous n'avez pas besoin d'effectuer d'action dans ce scénario.
* Le problème persiste après trois heures et l'état de la mise à niveau affiche *erreur* avec une bannière rouge. Vous pouvez reprendre la mise à niveau en sélectionnant *reprendre* après la résolution du problème.
* Le support NetApp a déterminé que la mise à niveau doit être provisoirement abandonnée pour prendre une action corrective avant une fenêtre de trois heures. Le support utilisera l'API pour annuler la mise à niveau.



CAUTION: L'abandon de la mise à niveau du cluster pendant la mise à jour d'un nœud peut entraîner le retrait non normal des disques du nœud. Si la suppression des disques n'est pas normale, le support NetApp implique une intervention manuelle de chaque fois que vous ajoutez des disques lors d'une mise à niveau. Il est possible que le nœud mette plus de temps à effectuer des mises à jour de firmware ou à effectuer des activités de synchronisation post-mise à jour. Si la progression de la mise à niveau semble bloquée, contactez le support NetApp pour obtenir de l'aide.



== Utilisez l'API de contrôle de cloud hybride NetApp pour mettre à niveau le firmware du stockage

Vous pouvez utiliser des API pour mettre à niveau les nœuds de stockage d'un cluster vers la version la plus récente du logiciel Element. Vous pouvez utiliser l'outil d'automatisation de votre choix pour exécuter les API. Le workflow d'API documenté ici utilise l'interface d'API REST disponible sur le nœud de gestion, par exemple.

.Étapes
. Effectuez l'une des opérations suivantes en fonction de votre connexion :
+
[cols="2*"]
|===
| Option | Étapes 


| Votre nœud de gestion dispose d'une connectivité externe.  a| 
.. Vérifiez la connexion au référentiel :
+
... Ouvrez l'interface de l'API REST du nœud de gestion sur le nœud de gestion :
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
... Sélectionnez *Authorise* et procédez comme suit :
+
.... Saisissez le nom d'utilisateur et le mot de passe du cluster.
.... Saisissez l'ID client en tant que `mnode-client`.
.... Sélectionnez *Autoriser* pour démarrer une session.
.... Fermez la fenêtre d'autorisation.


... Dans l'interface utilisateur de l'API REST, sélectionnez *GET ​/packages​/remote-repository​/connection*.
... Sélectionnez *essayez-le*.
... Sélectionnez *Exécuter*.
... Si le code 200 est renvoyé, passer à l'étape suivante. S'il n'y a pas de connexion au référentiel distant, établissez la connexion ou utilisez l'option site sombre.


.. Recherchez l'ID du package de mise à niveau :
+
... Dans l'interface utilisateur de l'API REST, sélectionnez *GET /packages*.
... Sélectionnez *essayez-le*.
... Sélectionnez *Exécuter*.
... Dans la réponse, copiez et enregistrez l'ID de pack du firmware pour une utilisation ultérieure.






| Votre nœud de gestion se trouve dans un site sombre sans connectivité externe.  a| 
.. Téléchargez le pack de mise à niveau du firmware de stockage le plus récent sur un périphérique accessible au nœud de gestion ; allez à la https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab/download/62654/Storage_Firmware_Bundle["Page de bundle du firmware du stockage du logiciel Element"^] et téléchargez l'image la plus récente du firmware de stockage.
.. Téléchargez le pack de mise à niveau du firmware de stockage sur le nœud de gestion :
+
... Ouvrez l'interface de l'API REST du nœud de gestion sur le nœud de gestion :
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
... Sélectionnez *Authorise* et procédez comme suit :
+
.... Saisissez le nom d'utilisateur et le mot de passe du cluster.
.... Saisissez l'ID client en tant que `mnode-client`.
.... Sélectionnez *Autoriser* pour démarrer une session.
.... Fermez la fenêtre d'autorisation.


... Dans l'interface utilisateur de l'API REST, sélectionnez *POST /packages*.
... Sélectionnez *essayez-le*.
... Sélectionnez *Parcourir* et sélectionnez le package de mise à niveau.
... Sélectionnez *Exécuter* pour lancer le téléchargement.
... Dans la réponse, copiez et enregistrez l'ID de package (`"id"`) pour une utilisation ultérieure.


.. Vérifiez l'état du chargement.
+
... Dans l'interface utilisateur de l'API REST, sélectionnez *GET​ /packages​/{ID}​/status*.
... Sélectionnez *essayez-le*.
... Saisissez l'ID du progiciel de micrologiciel que vous avez copié à l'étape précédente dans *ID*.
... Sélectionnez *Exécuter* pour lancer la demande d'état.
+
La réponse indique `state` comme `SUCCESS` une fois l'opération terminée.





|===
. Identifiez l'ID de ressource d'installation :
+
.. Ouvrez l'interface de l'API REST du nœud de gestion sur le nœud de gestion :
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Sélectionnez *Authorise* et procédez comme suit :
+
... Saisissez le nom d'utilisateur et le mot de passe du cluster.
... Saisissez l'ID client en tant que `mnode-client`.
... Sélectionnez *Autoriser* pour démarrer une session.
... Fermez la fenêtre d'autorisation.


.. Dans l'interface utilisateur de l'API REST, sélectionnez *OBTENIR /installations*.
.. Sélectionnez *essayez-le*.
.. Sélectionnez *Exécuter*.
.. Dans le cas d'une réponse, copiez l'ID de ressource d'installation (`id`).
+
[listing, subs="+quotes"]
----
*"id": "abcd01e2-xx00-4ccf-11ee-11f111xx9a0b",*
"management": {
  "errors": [],
  "inventory": {
    "authoritativeClusterMvip": "10.111.111.111",
    "bundleVersion": "2.14.19",
    "managementIp": "10.111.111.111",
    "version": "1.4.12"
----
.. Dans l'interface utilisateur de l'API REST, sélectionnez *GET /installations/{ID}*.
.. Sélectionnez *essayez-le*.
.. Collez l'ID de ressource d'installation dans le champ *ID*.
.. Sélectionnez *Exécuter*.
.. Dans le cas de, copiez et enregistrez l'ID de cluster de stockage (`"id"`) du cluster que vous envisagez de mettre à niveau pour une utilisation ultérieure.
+
[listing, subs="+quotes"]
----
"storage": {
  "errors": [],
  "inventory": {
    "clusters": [
      {
        "clusterUuid": "a1bd1111-4f1e-46zz-ab6f-0a1111b1111x",
        *"id": "a1bd1111-4f1e-46zz-ab6f-a1a1a111b012",*
----


. Exécutez la mise à niveau du micrologiciel de stockage :
+
.. Ouvrez l'interface de l'API REST de stockage sur le nœud de gestion :
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. Sélectionnez *Authorise* et procédez comme suit :
+
... Saisissez le nom d'utilisateur et le mot de passe du cluster.
... Saisissez l'ID client en tant que `mnode-client`.
... Sélectionnez *Autoriser* pour démarrer une session.
... Fermez la fenêtre.


.. Sélectionnez *POST /mises à niveau*.
.. Sélectionnez *essayez-le*.
.. Saisissez l'ID du package de mise à niveau dans le champ des paramètres.
.. Saisissez l'ID de cluster de stockage dans le champ paramètre.
.. Sélectionnez *Exécuter* pour lancer la mise à niveau.
+
La réponse doit indiquer l'état comme `initializing`:

+
[listing, subs="+quotes"]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  *"state": "initializing",*
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. Copiez l'ID de mise à niveau (`"upgradeId"`) qui fait partie de la réponse.


. Vérifier la progression et les résultats de la mise à niveau :
+
.. Sélectionnez *GET ​/upgrades/{upseId}*.
.. Sélectionnez *essayez-le*.
.. Saisissez l'ID de mise à niveau de l'étape précédente dans *mise à niveau Id*.
.. Sélectionnez *Exécuter*.
.. Procédez de l'une des manières suivantes en cas de problème ou d'exigence spéciale lors de la mise à niveau :
+
[cols="2*"]
|===
| Option | Étapes 


| Vous devez corriger les problèmes de santé du cluster dus à `failedHealthChecks` message dans le corps de la réponse.  a| 
... Consultez l'article de la base de connaissances spécifique répertorié pour chaque problème ou effectuez la solution spécifiée.
... Si vous spécifiez une base de connaissances, suivez la procédure décrite dans l'article correspondant de la base de connaissances.
... Après avoir résolu les problèmes de cluster, réauthentifier si nécessaire et sélectionner *PUT ​/upgrades/{upseId}*.
... Sélectionnez *essayez-le*.
... Saisissez l'ID de mise à niveau de l'étape précédente dans *mise à niveau Id*.
... Entrez `"action":"resume"` dans le corps de la demande.
+
[listing]
----
{
  "action": "resume"
}
----
... Sélectionnez *Exécuter*.




| Vous devez interrompre la mise à niveau, car la fenêtre de maintenance se ferme ou pour une autre raison.  a| 
... Réauthentifier si nécessaire et sélectionner *PUT ​/upgrades/{upseId}*.
... Sélectionnez *essayez-le*.
... Saisissez l'ID de mise à niveau de l'étape précédente dans *mise à niveau Id*.
... Entrez `"action":"pause"` dans le corps de la demande.
+
[listing]
----
{
  "action": "pause"
}
----
... Sélectionnez *Exécuter*.


|===
.. Exécutez l'API *GET ​/upgrades/{upseId}* plusieurs fois, selon les besoins, jusqu'à ce que le processus soit terminé.
+
Pendant la mise à niveau, le `status` indique `running` si aucune erreur n'est détectée. Lorsque chaque nœud est mis à niveau, le `step` la valeur passe à `NodeFinished`.

+
La mise à niveau a réussi une fois que l' `percent` la valeur est `100` et le `state` indique `finished`.





[discrete]
== Trouvez plus d'informations

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["Page Ressources NetApp HCI"^]

