---
sidebar: sidebar 
permalink: docs/task_nde_access_manual_ip.html 
summary: Découvrez comment accéder au moteur de déploiement NetApp en attribuant manuellement des adresses IP aux nœuds NetApp HCI. 
keywords: netapp, hci, netapp deployment engine, deployment, engine, deploy, access 
---
= Attribuez manuellement des adresses IP pour accéder au moteur de déploiement NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: hci, release notes, vcp, element, management services, firmware


[role="lead"]
Vous pouvez attribuer manuellement des adresses IPv4 statiques aux interfaces Bond1G et Bond10G sur tous les nœuds NetApp HCI pour accéder au moteur de déploiement NetApp et déployer NetApp HCI. Vous ne devez pas utiliser cette méthode sauf si votre réseau a des exigences spéciales.

.Ce dont vous avez besoin, 8217;ll
* Vous ou votre administrateur réseau avez terminé les tâches du document instructions d'installation et de configuration.
* Vous disposez d'un accès physique aux nœuds NetApp HCI.
* Tous les nœuds NetApp HCI sont sous tension.
* DHCP n'est pas activé pour les réseaux NetApp HCI et les nœuds NetApp HCI n'ont pas obtenu d'adresses IP auprès des serveurs DHCP. REMARQUE : toutes les adresses IP que vous attribuez manuellement avant d'utiliser le moteur de déploiement NetApp pour déployer le système sont temporaires et ne peuvent pas être réutilisées. Si vous choisissez d'attribuer manuellement des adresses IP, vous devez mettre de côté un deuxième ensemble permanent d'adresses IP inutilisées que vous pouvez attribuer lors du déploiement final.


Dans cette configuration, les nœuds de calcul et de stockage utiliseront des adresses IPv4 statiques pour découvrir et communiquer avec d'autres nœuds pendant le déploiement. Cette configuration n'est pas recommandée.

.Étapes
. Branchez une KVM à l'arrière de l'un des nœuds de stockage NetApp HCI (ce nœud deviendra le nœud de stockage de contrôle).
. Configurez l'adresse IP, le masque de sous-réseau et l'adresse de passerelle pour Bond1G et Bond10G dans l'interface utilisateur. Vous pouvez également configurer un ID VLAN pour chaque réseau si nécessaire.
. Répétez l'étape 2 pour les nœuds de calcul et de stockage restants.
. Ouvrez un navigateur Web sur un ordinateur qui peut accéder au réseau de gestion NetApp HCI.
. Accédez à l'adresse IP Bond1G que vous avez attribuée au nœud de stockage de contrôle. Par exemple :
+
[listing]
----
http://<Bond1G IP address>
----
+
Cela vous mène à l'interface utilisateur du moteur de déploiement NetApp.



[discrete]
== Trouvez plus d'informations

* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software["Versions du micrologiciel et du pilote dans les logiciels NetApp HCI et NetApp Element"^]

