---
sidebar: sidebar 
permalink: docs/task_nde_configure_credentials.html 
summary: Découvrez comment configurer VMware vSphere lors du déploiement de NetApp HCI. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= Configuration des identifiants NetApp HCI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Au cours du déploiement, vous définissez un ensemble d'identifiants à utiliser pour l'ensemble de l'environnement VMware vSphere récemment déployé, les ressources de calcul et de stockage NetApp HCI et le nœud de gestion. Si vous déployez NetApp HCI dans un environnement vSphere existant, ces informations d'identification ne sont pas appliquées au serveur vCenter existant.

.Description de la tâche
Rappelez-vous les points suivants concernant les informations d'identification que vous avez définies dans le moteur de déploiement NetApp HCI :

* *NetApp Hybrid Cloud Control (HCC) ou Element UI* : pour vous connecter à NetApp HCC ou à l'interface utilisateur Element lors du déploiement, utilisez le nom d'utilisateur et le mot de passe spécifiés dans cette étape du déploiement.
* *VMware vCenter* : pour vous connecter à vCenter (si installé dans le cadre du déploiement), utilisez le nom d'utilisateur avec le suffixe `@vsphere.local` ou le logiciel intégré `Administrator@vsphere.local` compte utilisateur et mot de passe spécifié dans cette étape de déploiement.
* *VMware ESXi* : pour vous connecter à ESXi sur les nœuds de calcul, utilisez le nom d'utilisateur `root` et le même mot de passe spécifié dans cette étape de déploiement.


Pour l'interaction avec les instances VMware vCenter, NetApp Hybrid Cloud Control utilise l'une des options suivantes :

* Les fonctions intégrées `Administrator@vsphere.local` Compte utilisateur sur l'instance vCenter installée dans le cadre du déploiement.
* Identifiants vCenter utilisés pour connecter le déploiement NetApp HCI à un serveur VMware vCenter existant.


.Étapes
. Sur la page *informations d'identification*, entrez un nom d'utilisateur dans le champ *Nom d'utilisateur*.
. Entrez un mot de passe dans le champ *Mot de passe*. Le mot de passe doit être conforme aux critères de mot de passe visibles dans la zone *Mot de passe doit contenir*.
. Confirmez le mot de passe dans le champ *Re-entrez Mot de passe*.
. Cliquez sur *Continuer*.


[discrete]
== Trouvez plus d'informations

* link:firmware_driver_versions.html["Versions de firmware et de pilote ESXi prises en charge pour les versions de NetApp HCI et de firmware pour les nœuds de stockage NetApp HCI"]
* Pour mettre à jour les informations d'identification vCenter et ESXi ultérieurement, reportez-vous à la section link:task_hci_credentials_vcenter_esxi.html["Mettre à jour les identifiants vCenter ou ESXi"].

