---
sidebar: sidebar 
permalink: docs/task_mnode_recover.html 
summary: 'Vous pouvez restaurer et redéployer un nœud de gestion pour votre cluster exécutant le logiciel NetApp Element. En fonction de votre configuration, vous devrez peut-être reconfigurer l"authentification pour le nœud de gestion.' 
keywords: netapp, element, management node, mnode, disaster recovery, redeploy, VM 
---
= Restaurez un nœud de gestion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez récupérer et redéployer manuellement le nœud de gestion de votre cluster exécutant le logiciel NetApp Element si votre précédent nœud de gestion utilisait des volumes persistants.

Vous pouvez déployer une nouvelle OVA et exécuter un script de redéploiement pour extraire les données de configuration à partir d'un nœud de gestion précédemment installé, exécutant la version 11.3 et les versions ultérieures.

.Ce dont vous avez besoin
* Votre ancien nœud de gestion exécutait la version 11.3 ou ultérieure du logiciel NetApp Element avec link:concept_hci_volumes.html#persistent-volumes["volumes persistants"] fonctionnalité engagée.
* Vous connaissez le MVIP et le SVIP du cluster contenant les volumes persistants.
* Votre version du cluster exécute NetApp Element 11.3 ou une version ultérieure.
* Votre installation utilise IPv4. Le nœud de gestion 11.3 ne prend pas en charge IPv6.
* Vous avez la permission de télécharger des logiciels sur le site de support NetApp.
* Vous avez identifié le type d'image de nœud de gestion approprié pour votre plate-forme :
+
[cols="30,30"]
|===
| Plateforme | Type d'image d'installation 


| Microsoft Hyper-V | .iso 


| KVM | .iso 


| VMware vSphere | .iso, .ova 


| Citrix XenServer | .iso 


| OpenStack | .iso 
|===


.Étapes
. <<Téléchargez ISO ou OVA et déployez la VM>>
. <<Configurez le réseau>>
. <<Configurer la synchronisation de l'heure>>
. <<Configurez le nœud de gestion>>




== Téléchargez ISO ou OVA et déployez la VM

. Téléchargez le fichier OVA ou ISO pour votre installation sur le https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["NetApp HCI"^] Sur le site de support NetApp :
+
.. Cliquez sur *Télécharger la dernière version* et acceptez le CLUF.
.. Sélectionnez l'image du nœud de gestion à télécharger.


. Si vous avez téléchargé l'OVA, procédez comme suit :
+
.. Déployer l'OVA.
.. Si votre cluster de stockage se trouve sur un sous-réseau distinct de votre nœud de gestion (eth0) et que vous souhaitez utiliser des volumes persistants, ajoutez un deuxième contrôleur d'interface réseau (NIC) à la machine virtuelle du sous-réseau de stockage (eth1, par exemple) ou assurez-vous que le réseau de gestion peut être acheminé vers le réseau de stockage.


. Si vous avez téléchargé l'ISO, procédez comme suit :
+
.. Créez une nouvelle machine virtuelle 64 bits à partir de votre hyperviseur avec la configuration suivante :
+
*** Six processeurs virtuels
*** 24 GO DE RAM
*** Disque virtuel 400 Go, provisionnement fin
*** Une interface réseau virtuelle avec accès à Internet et accès au MVIP de stockage.
*** Une interface réseau virtuelle avec un accès réseau de gestion au cluster de stockage. Si votre cluster de stockage se trouve sur un sous-réseau distinct de votre nœud de gestion (eth0) et que vous souhaitez utiliser des volumes persistants, ajoutez un deuxième contrôleur d'interface réseau (NIC) à la VM sur le sous-réseau de stockage (eth1) ou assurez-vous que le réseau de gestion peut être acheminé vers le réseau de stockage.
+

IMPORTANT: Ne mettez pas la machine virtuelle sous tension avant l'étape indiquant de le faire plus loin dans cette procédure.



.. Reliez l'ISO à la machine virtuelle et démarrez-le sur l'image d'installation .iso.
+

NOTE: L'installation d'un nœud de gestion à l'aide de l'image peut entraîner un délai de 30 secondes avant l'affichage de l'écran de démarrage.



. Mettez la machine virtuelle sous tension pour le nœud de gestion une fois l'installation terminée.




== Configurez le réseau

. À l'aide de l'interface utilisateur du terminal (TUI), créez un utilisateur d'administrateur de nœud de gestion.
+

TIP: Pour parcourir les options de menu, appuyez sur les touches fléchées vers le haut ou vers le bas. Pour parcourir les boutons, appuyez sur la touche Tab. Pour passer des boutons aux champs, appuyez sur la touche Tab. Pour naviguer entre les champs, appuyez sur les touches fléchées vers le haut ou vers le bas.

. Configurez le réseau de nœuds de gestion (eth0).
+

NOTE: Si vous avez besoin d'une carte réseau supplémentaire pour isoler le trafic de stockage, reportez-vous aux instructions de configuration d'une autre carte réseau : link:task_mnode_install_add_storage_NIC.html["Configuration d'une carte réseau de stockage (NIC)"].





== Configurer la synchronisation de l'heure

. Assurez-vous que le temps est synchronisé entre le nœud de gestion et le cluster de stockage à l'aide de NTP :



NOTE: À partir de l'élément 12.3.1, les sous-étapes (a) à (e) sont exécutées automatiquement. Pour le nœud de gestion 12.3.1, passez à la section <<substep_f_recover_config_time_sync,sous-étape (f)>> pour terminer la configuration de synchronisation de l'heure.

. Connectez-vous au nœud de gestion à l'aide de SSH ou de la console fournie par votre hyperviseur.
. Stop NTPD :
+
[listing]
----
sudo service ntpd stop
----
. Modifiez le fichier de configuration NTP `/etc/ntp.conf`:
+
.. Commenter les serveurs par défaut (`server 0.gentoo.pool.ntp.org`) en ajoutant un `#` devant chaque.
.. Ajoutez une nouvelle ligne pour chaque serveur de temps par défaut que vous souhaitez ajouter. Les serveurs de temps par défaut doivent être les mêmes serveurs NTP utilisés sur le cluster de stockage que ceux que vous utiliserez dans un link:task_mnode_recover.html#configure-the-management-node["plus tard"].
+
[listing]
----
vi /etc/ntp.conf

#server 0.gentoo.pool.ntp.org
#server 1.gentoo.pool.ntp.org
#server 2.gentoo.pool.ntp.org
#server 3.gentoo.pool.ntp.org
server <insert the hostname or IP address of the default time server>
----
.. Enregistrez le fichier de configuration une fois terminé.


. Forcer une synchronisation NTP avec le nouveau serveur ajouté.
+
[listing]
----
sudo ntpd -gq
----
. Redémarrez NTPD.
+
[listing]
----
sudo service ntpd start
----
. [[subSTEP_f_recover_config_time_sync]]Désactiver la synchronisation de l'heure avec l'hôte via l'hyperviseur (voici un exemple de VMware) :
+

NOTE: Si vous déployez le nœud M dans un environnement d'hyperviseur autre que VMware, par exemple, à partir de l'image .iso dans un environnement OpenStack, reportez-vous à la documentation de l'hyperviseur pour connaître les commandes équivalentes.

+
.. Désactiver la synchronisation périodique des heures :
+
[listing]
----
vmware-toolbox-cmd timesync disable
----
.. Afficher et confirmer l'état actuel du service :
+
[listing]
----
vmware-toolbox-cmd timesync status
----
.. Dans vSphere, vérifiez que `Synchronize guest time with host` La case n'est pas cochée dans les options VM.
+

NOTE: N'activez pas cette option si vous apportez de futures modifications à la machine virtuelle.






NOTE: Ne modifiez pas le NTP après avoir terminé la configuration de synchronisation de l'heure car elle affecte le NTP lorsque vous exécutez le <<step_6_recover_mnode_redeploy,commande redeploy>> sur le nœud de gestion.



== Configurez le nœud de gestion

. Créez un répertoire de destination temporaire pour le contenu du bundle de services de gestion :
+
[listing]
----
mkdir -p /sf/etc/mnode/mnode-archive
----
. Téléchargez le pack des services de gestion (version 2.15.28 ou ultérieure) précédemment installé sur le nœud de gestion existant et enregistrez-le dans le `/sf/etc/mnode/` répertoire.
. Extrayez le bundle téléchargé à l'aide de la commande suivante, en remplaçant la valeur entre [ ] parenthèses (y compris les crochets) par le nom du fichier de bundle :
+
[listing]
----
tar -C /sf/etc/mnode -xvf /sf/etc/mnode/[management services bundle file]
----
. Extrayez le fichier résultant dans le `/sf/etc/mnode-archive` répertoire :
+
[listing]
----
tar -C /sf/etc/mnode/mnode-archive -xvf /sf/etc/mnode/services_deploy_bundle.tar.gz
----
. Créez un fichier de configuration pour les comptes et les volumes :
+
[listing]
----
echo '{"trident": true, "mvip": "[mvip IP address]", "account_name": "[persistent volume account name]"}' | sudo tee /sf/etc/mnode/mnode-archive/management-services-metadata.json
----
+
.. Remplacer la valeur entre crochets [ ] (y compris les crochets) pour chacun des paramètres requis suivants :
+
*** *[adresse IP mvip]* : adresse IP virtuelle de gestion du cluster de stockage. Configurez le nœud de gestion avec le même cluster de stockage que vous avez utilisé pendant link:task_mnode_recover.html#configure-time-sync["Configuration de serveurs NTP"].
*** * [Nom du compte de volume persistant]* : nom du compte associé à tous les volumes persistants de ce cluster de stockage.




. Configurez et exécutez la commande de redéploiement de nœud de gestion pour vous connecter aux volumes persistants hébergés sur le cluster et démarrez les services avec les données de configuration de nœud de gestion précédentes :
+

NOTE: Vous serez invité à saisir des mots de passe dans une invite sécurisée. Si votre cluster est derrière un serveur proxy, vous devez configurer les paramètres proxy pour pouvoir accéder à un réseau public.

+
[listing]
----
/sf/packages/mnode/redeploy-mnode --mnode_admin_user [username]
----
+
.. Remplacez la valeur entre crochets [ ] (y compris les crochets) par le nom d'utilisateur du compte administrateur du nœud de gestion. Il s'agit probablement du nom d'utilisateur du compte utilisateur que vous avez utilisé pour vous connecter au nœud de gestion.
+

NOTE: Vous pouvez ajouter le nom d'utilisateur ou autoriser le script à vous demander les informations.

.. Exécutez le `redeploy-mnode` commande. Le script affiche un message de réussite lorsque le redéploiement est terminé.
.. Si vous accédez aux interfaces Web Element ou NetApp HCI (par exemple, le nœud de gestion ou le contrôle du cloud hybride NetApp) à l'aide du nom de domaine complet du système, link:task_hcc_upgrade_management_node.html#reconfigure-authentication-using-the-management-node-rest-api["reconfigurez l'authentification pour le nœud de gestion"].





IMPORTANT: Fonctionnalité SSH disponible link:task_mnode_enable_remote_support_connections.html["Accès à la session de tunnel de support à distance (RST) de NetApp"] est désactivé par défaut sur les nœuds de gestion exécutant les services de gestion 2.18 et versions ultérieures. Si vous aviez précédemment activé la fonctionnalité SSH sur le nœud de gestion, vous devrez peut-être la activer link:task_mnode_ssh_management.html["Désactivez de nouveau SSH"] sur le nœud de gestion restauré.

[discrete]
== En savoir plus

* link:concept_hci_volumes.html#persistent-volumes["Volumes persistants"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["Page Ressources NetApp HCI"^]

