---
sidebar: sidebar 
permalink: docs/task_rancher_upgrades.html 
summary: Vous pouvez utiliser le contrôle de cloud hybride NetApp pour mettre à niveau les composants de votre déploiement Rancher sur des systèmes NetApp HCI que vous avez installés précédemment avec HCC. 
keywords: netapp, hci, rancher, upgrade, hcc 
---
= Rancher mise à niveau sur NetApp HCI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour mettre à niveau le logiciel Rancher, vous pouvez utiliser l'interface utilisateur et l'API REST de NetApp Hybrid Cloud Control (HCC). HCC offre un processus simple de mise à niveau des composants de votre déploiement Rancher, y compris le serveur Rancher, le moteur Kubernetes Rancher (RKE) et l'OS de nœuds du cluster de gestion (pour les mises à jour de sécurité). Vous pouvez également utiliser l'API pour automatiser les mises à niveau.

Les mises à niveau sont disponibles par composant au lieu d'un package cumulatif. En tant que telles, certaines mises à niveau de composants telles que le système d'exploitation Ubuntu sont disponibles dans une cadence plus rapide. Les mises à niveau n'affectent que votre instance de serveur Rancher et le cluster de gestion sur lequel Rancher Server est déployé. Les mises à niveau vers le système d'exploitation Ubuntu du nœud de cluster de gestion ne concernent que les correctifs de sécurité critiques et ne mettent pas à niveau le système d'exploitation. Les clusters d'utilisateurs ne peuvent pas être mis à niveau à partir de NetApp Hybrid Cloud Control.

.Ce dont vous avez besoin, 8217;ll
* *Privilèges d'administrateur* : vous disposez des autorisations d'administrateur du cluster de stockage pour effectuer la mise à niveau.
* *Services de gestion*: Vous avez mis à jour votre bundle de services de gestion à la dernière version.



IMPORTANT: Vous devez effectuer une mise à niveau vers les derniers packs de services de gestion 2.17 ou version ultérieure pour bénéficier des fonctionnalités Rancher.

* *Ports système* : si vous utilisez le contrôle du cloud hybride NetApp pour les mises à niveau, vous avez vérifié que les ports nécessaires sont ouverts. Voir link:rancher_prereqs_overview.html#required-ports["Ports réseau"] pour en savoir plus.
* *Contrat de licence utilisateur final (CLUF)* : à partir des services de gestion 2.20.69, vous devez accepter et enregistrer le CLUF avant d'utiliser l'interface utilisateur ou l'API de contrôle de cloud hybride NetApp pour mettre à niveau un déploiement Rancher :
+
.. Ouvrez l'adresse IP du nœud de gestion dans un navigateur Web :
+
[listing]
----
https://<ManagementNodeIP>
----
.. Connectez-vous au contrôle de cloud hybride NetApp en fournissant les identifiants de l'administrateur du cluster de stockage.
.. Sélectionnez *Upgrade* en haut à droite de l'interface.
.. Le CLUF s'affiche. Faites défiler vers le bas, sélectionnez *J'accepte les mises à jour actuelles et futures*, puis sélectionnez *Enregistrer*.
+

NOTE: Lorsque vous acceptez le CLUF, il est enregistré pour toutes les mises à jour futures et la fonction de téléchargement automatique est activée. Vous recevrez des mises à jour sur les mises à jour et les mises à niveau logicielles NetApp que vous pouvez installer à votre discrétion et à votre convenance. Vous pouvez désactiver la fonctionnalité de téléchargement automatique en désactivant la connectivité réseau au référentiel logiciel en ligne de NetApp.





Choisissez l'un des processus de mise à niveau suivants :

*  NetApp Hybrid Cloud Control UI to upgrade a Rancher deployment
*  NetApp Hybrid Cloud Control API to upgrade a Rancher deployment




== Utilisez l'interface utilisateur de contrôle de cloud hybride NetApp pour mettre à niveau un déploiement Rancher

Grâce à l'interface utilisateur de contrôle des clouds hybrides NetApp, vous pouvez mettre à niveau tous ces composants dans votre déploiement Rancher :

* Serveur de rancher
* Rancher Kubernetes Engine (RKE)
* Mises à jour de sécurité du système d'exploitation des nœuds


.Ce dont vous avez besoin, 8217;ll
* Une bonne connexion Internet. Les mises à niveau des sites sombres (mises à niveau sur un site sans connectivité externe) ne sont pas disponibles.


.Étapes
. Ouvrez l'adresse IP du nœud de gestion dans un navigateur Web :
+
[listing]
----
https://<ManagementNodeIP>
----
. Connectez-vous au contrôle de cloud hybride NetApp en fournissant les identifiants de l'administrateur du cluster de stockage.
. Sélectionnez *Upgrade* en haut à droite de l'interface.
. Sur la page *mises à niveau*, sélectionnez *Rancher*.
. Sélectionnez le menu *actions* pour le logiciel que vous souhaitez mettre à niveau.
+
** Serveur de rancher
** Rancher Kubernetes Engine (RKE)
** Mises à jour de sécurité du système d'exploitation des nœuds


. Sélectionnez *Upgrade* pour les mises à niveau Rancher Server ou RKE ou *Apply Upgrade* pour les mises à jour de sécurité des systèmes d'exploitation de nœud.
+

NOTE: Pour le système d'exploitation de nœud, les mises à niveau sans surveillance des correctifs de sécurité sont exécutées quotidiennement, mais le nœud n'est pas redémarré automatiquement. En appliquant des mises à niveau, vous redémarrez chaque nœud pour que les mises à jour de sécurité prennent effet.



Une bannière s'affiche pour indiquer que la mise à niveau du composant a réussi. Un délai de 2 minutes peut s'avérer nécessaire avant que l'interface utilisateur de NetApp Hybrid Cloud Control affiche le numéro de version mis à jour.



== Utilisez l'API de contrôle de cloud hybride NetApp pour mettre à niveau un déploiement Rancher

Vous pouvez utiliser des API pour mettre à niveau tous ces composants dans votre déploiement Rancher :

* Serveur de rancher
* Rancher Kubernetes Engine (RKE)
* Nœud OS (pour les mises à jour de sécurité)


Vous pouvez utiliser un outil d'automatisation de votre choix pour exécuter les API ou l'interface utilisateur de l'API REST disponible sur le nœud de gestion.

.Options
*  Rancher Server
*  RKE
*  node OS security updates
+

NOTE: Pour le système d'exploitation de nœud, les mises à niveau sans surveillance des correctifs de sécurité sont exécutées quotidiennement, mais le nœud n'est pas redémarré automatiquement. En appliquant des mises à niveau, vous redémarrez chaque nœud pour que les mises à jour de sécurité prennent effet.





=== Mettre à niveau Rancher Server

.Commandes d'API
. Lancez la demande de mise à niveau de la liste :
+
[listing]
----
curl -X POST "https://<managementNodeIP>/k8sdeployer/1/upgrade/rancher-versions" -H "accept: application/json" -H "Authorization: Bearer ${TOKEN}"
----
+

NOTE: Vous pouvez trouver le porteur `${TOKEN}` Utilisé par la commande API lorsque vous link:task_mnode_api_get_authorizationtouse.html["autoriser"]. Le porteur `${TOKEN}` est dans la réponse curl.

. Obtenir l'état de la tâche à l'aide de l'ID de tâche de la commande précédente et copier le numéro de version le plus récent de la réponse :
+
[listing]
----
curl -X GET "https://<mNodeIP>/k8sdeployer/1/task/<taskID>" -H "accept: application/json" -H "Authorization: Bearer ${TOKEN}"
----
. Lancez une demande de mise à niveau de serveur Rancher :
+
[listing]
----
curl -X PUT "https://<mNodeIP>/k8sdeployer/1/upgrade/rancher/<version number>" -H "accept: application/json" -H "Authorization: Bearer"
----
. Obtenir le statut de la tâche à l'aide de l'ID de tâche à partir de la réponse de la commande de
+
[listing]
----
curl -X GET "https://<mNodeIP>/k8sdeployer/1/task/<taskID>" -H "accept: application/json" -H "Authorization: Bearer ${TOKEN}"
----


.ÉTAPES DE L'INTERFACE UTILISATEUR DE L'API REST
. Ouvrez l'interface de l'API REST du nœud de gestion sur le nœud de gestion :
+
[listing]
----
https://<ManagementNodeIP>/k8sdeployer/api/
----
. Sélectionnez *Authorise* et procédez comme suit :
+
.. Saisissez le nom d'utilisateur et le mot de passe du cluster.
.. Saisissez l'ID client en tant que `mnode-client`.
.. Sélectionnez *Autoriser* pour démarrer une session.
.. Fermez la fenêtre d'autorisation.


. Recherchez la dernière mise à niveau :
+
.. À partir de l'interface utilisateur de l'API REST, exécutez *POST /upgrade​/rancher-versions*.
.. Dans la réponse, copiez l'ID de tâche.
.. Exécutez *GET /task​/{taskID}* avec l'ID de tâche de l'étape précédente.


. À partir de la réponse */task​/{taskID}*, copiez le numéro de version le plus récent que vous souhaitez utiliser pour la mise à niveau.
. Exécutez la mise à niveau Rancher Server :
+
.. À partir de l'interface utilisateur de l'API REST, exécutez *PUT /upgrade​/rancher​/{version}* avec le numéro de version le plus récent de l'étape précédente.
.. Dans la réponse, copiez l'ID de tâche.
.. Exécutez *GET /task​/{taskID}* avec l'ID de tâche de l'étape précédente.




La mise à niveau a réussi une fois que l' `PercentComplete` indique `100` et `results` indique le numéro de version mis à niveau.



=== Mise à niveau de la télécommande RKE

.Commandes d'API
. Lancez la demande de mise à niveau de la liste :
+
[listing]
----
curl -X POST "https://<mNodeIP>/k8sdeployer/1/upgrade/rke-versions" -H "accept: application/json" -H "Authorization: Bearer ${TOKEN}"
----
+

NOTE: Vous pouvez trouver le porteur `${TOKEN}` Utilisé par la commande API lorsque vous link:task_mnode_api_get_authorizationtouse.html["autoriser"]. Le porteur `${TOKEN}` est dans la réponse curl.

. Obtenir l'état de la tâche à l'aide de l'ID de tâche de la commande précédente et copier le numéro de version le plus récent de la réponse :
+
[listing]
----
curl -X GET "https://<mNodeIP>/k8sdeployer/1/task/<taskID>" -H "accept: application/json" -H "Authorization: Bearer ${TOKEN}"
----
. Lancez la demande de mise à niveau de la télécommande de télédéverrouillage
+
[listing]
----
curl -X PUT "https://<mNodeIP>/k8sdeployer/1/upgrade/rke/<version number>" -H "accept: application/json" -H "Authorization: Bearer"
----
. Obtenir le statut de la tâche à l'aide de l'ID de tâche à partir de la réponse de la commande de
+
[listing]
----
curl -X GET "https://<mNodeIP>/k8sdeployer/1/task/<taskID>" -H "accept: application/json" -H "Authorization: Bearer ${TOKEN}"
----


.ÉTAPES DE L'INTERFACE UTILISATEUR DE L'API REST
. Ouvrez l'interface de l'API REST du nœud de gestion sur le nœud de gestion :
+
[listing]
----
https://<ManagementNodeIP>/k8sdeployer/api/
----
. Sélectionnez *Authorise* et procédez comme suit :
+
.. Saisissez le nom d'utilisateur et le mot de passe du cluster.
.. Saisissez l'ID client en tant que `mnode-client`.
.. Sélectionnez *Autoriser* pour démarrer une session.
.. Fermez la fenêtre d'autorisation.


. Recherchez la dernière mise à niveau :
+
.. À partir de l'interface utilisateur de l'API REST, exécutez *POST /upgrade​/rke-versions*.
.. Dans la réponse, copiez l'ID de tâche.
.. Exécutez *GET /task​/{taskID}* avec l'ID de tâche de l'étape précédente.


. À partir de la réponse */task​/{taskID}*, copiez le numéro de version le plus récent que vous souhaitez utiliser pour la mise à niveau.
. Exécutez la mise à jour RKE :
+
.. À partir de l'interface utilisateur de l'API REST, exécutez *PUT /upgrade/rke/{version}* avec le numéro de version le plus récent de l'étape précédente.
.. Copiez l'ID de tâche depuis la réponse.
.. Exécutez *GET /task​/{taskID}* avec l'ID de tâche de l'étape précédente.




La mise à niveau a réussi une fois que l' `PercentComplete` indique `100` et `results` indique le numéro de version mis à niveau.



=== Appliquer les mises à jour de sécurité du système d'exploitation des nœuds

.Commandes d'API
. Lancez la demande de vérification des mises à niveau :
+
[listing]
----
curl -X GET "https://<mNodeIP>/k8sdeployer/1/upgrade/checkNodeUpdates" -H "accept: application/json" -H "Authorization: Bearer ${TOKEN}"
----
+

NOTE: Vous pouvez trouver le porteur `${TOKEN}` Utilisé par la commande API lorsque vous link:task_mnode_api_get_authorizationtouse.html["autoriser"]. Le porteur `${TOKEN}` est dans la réponse curl.

. Obtenir l'état de la tâche à l'aide de l'ID de tâche de la commande précédente et vérifier qu'un numéro de version plus récent est disponible à partir de la réponse :
+
[listing]
----
curl -X GET "https://<mNodeIP>/k8sdeployer/1/task/<taskID>" -H "accept: application/json" -H "Authorization: Bearer ${TOKEN}"
----
. Appliquer les mises à jour du nœud :
+
[listing]
----
curl -X POST "https://<mNodeIP>/k8sdeployer/1/upgrade/applyNodeUpdates" -H "accept: application/json" -H "Authorization: Bearer"
----
+

NOTE: Pour le système d'exploitation de nœud, les mises à niveau sans surveillance des correctifs de sécurité sont exécutées quotidiennement, mais le nœud n'est pas redémarré automatiquement. En appliquant des mises à niveau, vous redémarrez chaque nœud de façon séquentielle afin que les mises à jour de sécurité prennent effet.

. Obtenir le statut de la tâche à l'aide de l'ID de tâche de la mise à niveau `applyNodeUpdates` réponse :
+
[listing]
----
curl -X GET "https://<mNodeIP>/k8sdeployer/1/task/<taskID>" -H "accept: application/json" -H "Authorization: Bearer ${TOKEN}"
----


.ÉTAPES DE L'INTERFACE UTILISATEUR DE L'API REST
. Ouvrez l'interface de l'API REST du nœud de gestion sur le nœud de gestion :
+
[listing]
----
https://<ManagementNodeIP>/k8sdeployer/api/
----
. Sélectionnez *Authorise* et procédez comme suit :
+
.. Saisissez le nom d'utilisateur et le mot de passe du cluster.
.. Saisissez l'ID client en tant que `mnode-client`.
.. Sélectionnez *Autoriser* pour démarrer une session.
.. Fermez la fenêtre d'autorisation.


. Vérifiez si un package de mise à niveau est disponible :
+
.. Dans l'interface utilisateur de l'API REST, exécutez *GET /upgrade/checkNodeUpdates*.
.. Dans la réponse, copiez l'ID de tâche.
.. Exécutez *GET /task​/{taskID}* avec l'ID de tâche de l'étape précédente.
.. Dans la réponse */task​/{taskID}*, vérifiez que le numéro de version est plus récent que celui actuellement appliqué à vos noeuds.


. Appliquer les mises à niveau du système d'exploitation des nœuds :
+

NOTE: Pour le système d'exploitation de nœud, les mises à niveau sans surveillance des correctifs de sécurité sont exécutées quotidiennement, mais le nœud n'est pas redémarré automatiquement. En appliquant des mises à niveau, vous redémarrez chaque nœud de façon séquentielle afin que les mises à jour de sécurité prennent effet.

+
.. À partir de l'interface utilisateur de l'API REST, exécutez *POST /upgrade​/applyNodeUpdates*.
.. Dans la réponse, copiez l'ID de tâche.
.. Exécutez *GET /task​/{taskID}* avec l'ID de tâche de l'étape précédente.
.. Dans la réponse */task​/{taskID}*, vérifiez que la mise à niveau a été appliquée.




La mise à niveau a réussi une fois que l' `PercentComplete` indique `100` et `results` indique le numéro de version mis à niveau.

[discrete]
== Trouvez plus d'informations

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["Page Ressources NetApp HCI"^]

