---
sidebar: sidebar 
permalink: docs/task_mnode_work_overview.html 
summary: 'Vous pouvez utiliser le nœud de gestion (nœud M) pour utiliser les services système, gérer les ressources et les paramètres du cluster, exécuter des tests et des utilitaires système, configurer Active IQ pour le contrôle du système et activer l"accès au support NetApp pour le dépannage.' 
keywords: netapp, mnode, api, rest api, mnode ui, management node ui 
---
= Présentation du nœud de gestion
:allow-uri-read: 


[role="lead"]
Vous pouvez utiliser le nœud de gestion (nœud M) pour utiliser les services système, gérer les ressources et les paramètres du cluster, exécuter des tests et des utilitaires système, configurer Active IQ pour le contrôle du système et activer l'accès au support NetApp pour le dépannage.


NOTE: Il est recommandé d'associer un seul nœud de gestion à une instance VMware vCenter et d'éviter de définir les mêmes ressources de stockage et de calcul ou instances vCenter dans plusieurs nœuds de gestion.

Pour les clusters exécutant Element 11.3 ou version ultérieure, vous pouvez travailler avec le nœud de gestion à l'aide de l'une des deux interfaces suivantes :

* Grâce à l'interface du nœud de gestion (`https://[mNode IP]:442`), vous pouvez modifier les paramètres du réseau et du cluster, exécuter des tests système ou utiliser des utilitaires système.
* Grâce à l'interface utilisateur d'API REST intégrée (`https://[mNode IP]/mnode`), vous pouvez exécuter ou comprendre des API relatives aux services de nœud de gestion, y compris la configuration du serveur proxy, les mises à jour du niveau de service ou la gestion des ressources.


Installez ou restaurez un nœud de gestion :

* link:task_mnode_install.html["Installez un nœud de gestion"]
* link:task_mnode_install_add_storage_NIC.html["Configuration d'une carte réseau de stockage (NIC)"]
* link:task_mnode_recover.html["Restaurez un nœud de gestion"]


Accéder au nœud de gestion :

* link:task_mnode_access_ui.html["Accès au nœud de gestion (interface utilisateur ou API REST)"]


Modifiez le certificat SSL par défaut :

* link:reference_change_mnode_default_ssl_certificate.html["Modifiez le certificat SSL par défaut du nœud de gestion"]


Effectuez des tâches à l'aide de l'interface du nœud de gestion :

* link:task_mnode_work_overview_UI.html["Présentation de l'interface du nœud de gestion"]


Exécutez des tâches à l'aide des API REST de nœud de gestion :

* link:task_mnode_work_overview_API.html["Présentation de l'interface de l'API REST du nœud de gestion"]


Désactivez ou activez la fonctionnalité SSH à distance ou démarrez une session de tunnel de support à distance avec le support NetApp pour vous aider à résoudre les problèmes suivants :

* link:task_mnode_enable_remote_support_connections.html["Activation des connexions à distance au support NetApp"]
* link:task_mnode_ssh_management.html["Gérez la fonctionnalité SSH sur le nœud de gestion"]




== Trouvez plus d'informations

https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]
