---
sidebar: sidebar 
permalink: docs/task_nde_configure_net_settings.html 
summary: Découvrez comment configurer les paramètres réseau de déploiement NetApp HCI. 
keywords: netapp, hci, deployment, compatibility, nodes 
---
= Configurez les paramètres réseau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI fournit une page de paramètres réseau comportant plusieurs sections afin de simplifier la configuration du réseau. Vous pouvez passer par chaque section et entrer des informations ou attribuer des adresses IP pour les hôtes et les nœuds de chaque réseau.

.Ce dont vous avez besoin, 8217;ll
* Vous avez obtenu les informations suivantes :
+
** Préfixe de nom planifié pour les hôtes et le cluster de stockage
** Tous les masques de sous-réseau planifiés, le démarrage de l'adresse IP, de la passerelle par défaut et les ID de VLAN pour les réseaux de gestion, iSCSI et vMotion
** Le masque de sous-réseau, l'adresse IP, la passerelle par défaut et les ID de VLAN pour tout déploiement VMware vCenter planifié
** Adresse du serveur NTP (Network Time Protocol) pour NetApp HCI
** Informations d'adresse IP du serveur DNS pour NetApp HCI


* Si vous déployez un commutateur distribué vSphere, vous disposez d'une licence vSphere Enterprise plus prête à être appliquée une fois le déploiement terminé.
* Si vous avez attribué des ID VLAN aux ports de nœud lors de la configuration de l'interface utilisateur de terminal (TUI), vous avez configuré ces ports avec le même ID VLAN lors de la configuration du réseau. Il n'est pas nécessaire de configurer des ports hôtes balisés en tant que ports d'accès ou VLAN natifs sur les ports de commutateur connectés.
* Vous avez vérifié que la configuration de votre commutateur réseau est correcte. Des configurations de commutateur incorrectes (par exemple, des VLAN ou une taille MTU incorrecte) causeront des erreurs de déploiement.


Si vous avez sélectionné la topologie réseau à deux câbles pour les nœuds de calcul, vous devez utiliser des ID VLAN pour les réseaux vMotion et de stockage pour tous les nœuds de calcul et de stockage du déploiement (les ID VLAN sont facultatifs pour les réseaux de gestion). Notez que NetApp HCI valide les adresses IP que vous entrez au cours de ces étapes, mais vous pouvez désactiver cette validation à l'aide du bouton *validation réseau en direct est*. NetApp HCI vérifie également les autres informations saisies lors de ces étapes : par exemple, s'assurer qu'aucun sous-réseau ne se chevauchent, s'assurant qu'aucun ID de VLAN n'est attribué à plusieurs réseaux et d'autres validations de base.


NOTE: Dans les environnements qui nécessitent le balisage VLAN côté hôte avant le déploiement, si vous avez configuré des ID de VLAN sur des nœuds de calcul et de stockage afin qu'ils soient détectables par le moteur de déploiement NetApp, veillez à utiliser les VLAN appropriés lors de la configuration des paramètres réseau dans le moteur de déploiement NetApp.

Si vous déployez un cluster de stockage à deux ou trois nœuds, vous pouvez compléter les informations d'adresse IP des nœuds témoin sur la page *Paramètres réseau*.


NOTE: Dans les pages d'affectation d'adresse IP, les informations saisies en mode *attribuer automatiquement des adresses IP* n'affectent pas les informations saisies en mode *attribuer manuellement des adresses IP*, et vice versa. Si vous entrez des adresses IP dans les deux modes, NetApp HCI utilise les informations d'adresse IP dans n'importe quel mode actif lorsque vous cliquez sur *Continuer* en bas de la page.

NetApp HCI vérifie les informations saisies sur ces pages. Voici quelques problèmes courants et solutions de contournement :

|===
| Problème | Solution de contournement 


| En mode d'attribution automatique d'adresse IP, le message s'affiche après la saisie d'une adresse IP de départ `IPs in the range are in use:` Avec une liste déroulante des adresses IP utilisées. | NetApp HCI a attribué une plage contiguë d'adresses IP, mais une ou plusieurs de ces adresses IP sont déjà utilisées. Libérez les adresses IP utilisées et réessayez, ou utilisez le mode d'attribution manuelle d'adresses IP pour attribuer des adresses IP spécifiques. 


| Après avoir saisi une passerelle par défaut, le message s'affiche `The gateway is not valid`.  a| 
L'adresse IP de la passerelle par défaut ne correspond pas au sous-réseau que vous avez fourni ou il y a un problème avec le réseau ou le serveur que vous devez résoudre. Pour plus d'informations, consultez les articles suivants de la base de connaissances NetApp :

* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Troubleshoot_Invalid_Gateway_in_NDE["Dépanner une passerelle non valide dans le moteur de déploiement NetApp"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/%22The_gateway_is_not_valid%22_during_NDE["La passerelle n'est pas valide dans le moteur de déploiement NetApp"^]




| Vous avez terminé plusieurs pages de configuration *Network Settings* et vous rendez compte que des informations incorrectes sont affichées sur l'une des pages précédentes dans l'ordre. | En utilisant la séquence de pages numérotées en haut de la page, vous pouvez sélectionner une page que vous avez déjà terminée et y modifier les informations. Lorsque vous avez terminé, vous pouvez cliquer sur *Continuer* sur les pages terminées pour revenir à la page actuelle. 
|===


== Configurez les paramètres DNS et NTP

.Étapes
. Sur la page *DNS/NTP*, entrez les informations sur les serveurs DNS et NTP pour NetApp HCI dans les champs suivants :
+
|===
| Champ | Description 


| *Adresse IP du serveur DNS 1* | L'adresse IP du serveur DNS principal pour NetApp HCI. Si vous avez spécifié un serveur DNS sur la page de configuration de vCenter, ce champ est renseigné et en lecture seule. 


| *Adresse IP du serveur DNS 2 (facultatif)* | Adresse IP facultative d'un serveur DNS secondaire pour NetApp HCI. 


| *Adresse serveur NTP 1* | L'adresse IP ou le nom de domaine complet du serveur NTP principal de cette infrastructure. 


| *Adresse du serveur NTP 2 (facultatif)* | Adresse IP facultative ou nom de domaine complet du serveur NTP secondaire pour cette infrastructure. 
|===




== Attribuez des ID de VLAN

Sur la page *ID de VLAN*, vous pouvez attribuer des ID de VLAN aux réseaux NetApp HCI. Vous pouvez également choisir de ne pas utiliser d'ID de VLAN. Si vous avez sélectionné la topologie réseau à deux câbles pour les nœuds de calcul, vous devez utiliser des ID VLAN pour les réseaux vMotion et de stockage pour tous les nœuds de calcul et de stockage du déploiement (les ID VLAN sont facultatifs pour les réseaux de gestion).


NOTE: Lorsque vous attribuez des ID de VLAN, vous configurez des balises VLAN que NetApp HCI appliquera au trafic réseau. Il n'est pas nécessaire de saisir votre VLAN natif comme ID VLAN ; pour utiliser le VLAN natif pour un réseau, laissez le champ approprié vide.

Choisissez l'une des options suivantes :

|===
| Option | Étapes 


| Attribuez des ID de VLAN  a| 
. Sélectionnez *Oui* pour l'option *affectera des ID de VLAN*.
. Dans la colonne *VLAN ID*, entrez une balise VLAN à utiliser pour chaque type de trafic réseau que vous souhaitez attribuer à un VLAN.
+
Le trafic vMotion de calcul et le trafic iSCSI doivent utiliser un ID VLAN non partagé.

. Cliquez sur *Continuer*.




| N'attribuez pas d'ID de VLAN  a| 
. Sélectionnez *non* pour l'option *attribuera-la des ID de VLAN*.
. Cliquez sur *Continuer*.


|===


== Configurez le réseau de gestion

Sur la page *Management*, vous pouvez choisir de renseigner NetApp HCI automatiquement les plages d'adresses IP des réseaux de gestion en fonction d'une adresse IP de départ ou de saisir manuellement toutes les informations d'adresse IP.

Choisissez l'une des options suivantes :

|===
| Option | Étapes 


| Attribuez automatiquement des adresses IP  a| 
. Sélectionnez l'option *attribuer automatiquement des adresses IP*.
. Dans la colonne *Subnet*, entrez une définition de sous-réseau au format CIDR pour chaque VLAN.
. Dans la colonne *Default Gateway*, entrez une passerelle par défaut pour chaque VLAN.
. Dans la colonne *Subnet*, entrez une adresse IP de départ à utiliser pour chaque VLAN et type de nœud.
+
NetApp HCI remplit automatiquement les adresses IP de fin pour chaque hôte ou groupe d'hôtes.

. Cliquez sur *Continuer*.




| Attribuez manuellement des adresses IP  a| 
. Sélectionnez l'option *attribuer manuellement des adresses IP*.
. Dans la colonne *Subnet*, entrez une définition de sous-réseau au format CIDR pour chaque VLAN.
. Dans la colonne *Default Gateway*, entrez une passerelle par défaut pour chaque VLAN.
. Dans la ligne de chaque hôte ou nœud, entrez l'adresse IP de cet hôte ou nœud.
. Saisissez l'adresse MVIP (Management Virtual IP) du réseau de gestion.
. Cliquez sur *Continuer*.


|===


== Configuration du réseau vMotion

Sur la page *vMotion*, vous pouvez choisir de renseigner NetApp HCI automatiquement les plages d'adresses IP pour le réseau vMotion en fonction d'une adresse IP de départ. Vous pouvez également choisir de saisir manuellement toutes les informations d'adresse IP.

Choisissez l'une des options suivantes :

|===
| Option | Étapes 


| Attribuez automatiquement des adresses IP  a| 
. Sélectionnez l'option *attribuer automatiquement des adresses IP*.
. Dans la colonne *Subnet*, entrez une définition de sous-réseau au format CIDR pour chaque VLAN.
. (Facultatif) dans la colonne *Default Gateway* (passerelle par défaut), saisissez une passerelle par défaut pour chaque VLAN.
. Dans la colonne *Subnet*, entrez une adresse IP de départ à utiliser pour chaque VLAN et type de nœud.
+
NetApp HCI remplit automatiquement les adresses IP de fin pour chaque hôte ou groupe d'hôtes.

. Cliquez sur *Continuer*.




| Attribuez manuellement des adresses IP  a| 
. Sélectionnez l'option *attribuer manuellement des adresses IP*.
. Dans la colonne *Subnet*, entrez une définition de sous-réseau au format CIDR pour chaque VLAN.
. (Facultatif) dans la colonne *Default Gateway* (passerelle par défaut), saisissez une passerelle par défaut pour chaque VLAN.
. Dans la ligne de chaque hôte ou nœud, entrez l'adresse IP de cet hôte ou nœud.
. Cliquez sur *Continuer*.


|===


== Configurez le réseau iSCSI

Sur la page *iSCSI*, vous pouvez choisir de faire remplir automatiquement les plages d'adresses IP du réseau iSCSI par NetApp HCI en fonction d'une adresse IP de départ, ou de saisir manuellement toutes les informations d'adresse IP.

Choisissez l'une des options suivantes :

|===
| Option | Étapes 


| Attribuez automatiquement des adresses IP  a| 
. Sélectionnez l'option *attribuer automatiquement des adresses IP*.
. Dans la colonne *Subnet*, entrez une définition de sous-réseau au format CIDR pour le réseau iSCSI.
. (Facultatif) dans la colonne *Default Gateway* (passerelle par défaut), entrez une passerelle par défaut pour le réseau iSCSI.
. Dans la colonne *sous-réseau*, entrez une adresse IP de départ à utiliser pour chaque type de nœud.
+
NetApp HCI remplit automatiquement les adresses IP de fin pour chaque hôte ou groupe d'hôtes.

. Cliquez sur *Continuer*.




| Attribuez manuellement des adresses IP  a| 
. Sélectionnez l'option *attribuer manuellement des adresses IP*.
. Dans la colonne *Subnet*, entrez une définition de sous-réseau au format CIDR pour le réseau iSCSI.
. (Facultatif) dans la colonne *Default Gateway* (passerelle par défaut), entrez une passerelle par défaut pour le réseau iSCSI.
. Dans la section *Management Node*, entrez une adresse IP pour le noeud de gestion.
. Pour chaque nœud de la section *nœuds de calcul*, entrez les adresses IP iSCSI A et iSCSI B.
. Dans la ligne *Storage Virtual IP (SVIP)*, entrez l'adresse IP SVIP du réseau iSCSI.
. Dans les lignes restantes, pour chaque hôte ou nœud, entrez l'adresse IP de cet hôte ou nœud.
. Cliquez sur *Continuer*.


|===


== Attribuez des noms de clusters et d'hôtes

Sur la page *Naming*, vous pouvez choisir d'indiquer automatiquement le nom du cluster et les noms des nœuds du cluster dans NetApp HCI, en fonction d'un préfixe de nom, ou d'entrer manuellement tous les noms du cluster et des nœuds.

Choisissez l'une des options suivantes :

|===
| Option | Étapes 


| Attribuez automatiquement des noms de clusters et d'hôtes  a| 
. Sélectionnez l'option *attribuer automatiquement des noms de cluster / d'hôte*.
. Dans la section *préfixe d'installation*, entrez un préfixe de nom à utiliser pour tous les noms d'hôte de nœud du cluster (y compris le nœud de gestion et les nœuds témoins).
+
NetApp HCI renseigne automatiquement les noms des hôtes en fonction du type de nœud, ainsi que des suffixes pour les noms de nœud courants (nœuds de calcul et de stockage, par exemple).

. (Facultatif) dans la colonne *Naming Scheme*, modifiez l'un des noms résultants pour les hôtes.
. Cliquez sur *Continuer*.




| Attribuer manuellement des noms de clusters et d'hôtes  a| 
. Sélectionnez l'option *attribuer manuellement des noms de cluster / d'hôte*.
. Dans la colonne *Host / Cluster Name*, entrez le nom d'hôte pour chaque hôte et un nom de cluster pour le cluster de stockage.
. Cliquez sur *Continuer*.


|===


== Trouvez plus d'informations

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]
* https://www.netapp.com/us/documentation/hci.aspx["Page Ressources NetApp HCI"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentation SolidFire et Element"^]

