---
sidebar: sidebar 
permalink: docs/task_nde_configure_new_vsphere.html 
summary: Découvrez comment configurer VMware vSphere lors du déploiement de NetApp HCI. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= Configuration d'un nouvel environnement VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, netapp deployment engine, deployment, vsphere


[role="lead"]
Vous pouvez déployer un nouvel environnement vSphere dans le cadre du processus d'installation de NetApp HCI en fournissant certaines des informations réseau que vSphere doit utiliser. Notez que si vous configurez vSphere à l'aide d'une adresse IP, celle-ci ne peut pas être modifiée après l'installation.

Vous avez obtenu les informations réseau pour l'environnement vSphere planifié.

.Étapes
. Cliquez sur *configurer un nouveau déploiement vSphere*.
. Sélectionnez la version de vSphere que le système doit installer pendant le déploiement.
. Configurez le nouvel environnement vSphere à l'aide de l'une des options suivantes :
+
|===
| Option | Étapes 


| Utilisez un nom de domaine (recommandé).  a| 
.. Cliquez sur *configurer en utilisant un nom de domaine complet*.
.. Entrez le nom de domaine de vCenter Server dans le champ *vCenter Server Nom de domaine complet*.
.. Entrez l'adresse IP du serveur DNS dans le champ *adresse IP du serveur DNS*.
.. Cliquez sur *Continuer*.




| Utiliser une adresse IP.  a| 
.. Cliquez sur *configurer à l'aide d'une adresse IP*.
.. Cliquez sur *Continuer*.


|===


[discrete]
== Trouvez plus d'informations

* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software["Versions du micrologiciel et du pilote dans les logiciels NetApp HCI et NetApp Element"^]

